train_mode: "finetune"

training_model_parameters:
    goal_loss_weight: 1
    collision_loss_weight: 10

data_module_parameters:
  data_dir: /data/cabinet_6k
  trajectory_key: 'global_solutions'
  num_obstacle_points: 4096
  num_target_points: 128
  random_scale: 0

shared_parameters:
    num_robot_points: 2048

model_path: /workspace/mpinets_finetune_mpinets_hybrid_training_data_small_hybrid_finetuned_on_small/sp2hrle1/epoch=14-step=17040.ckpt
checkpoint_interval: 10
validation_interval: 10
gpus: 1 # If > 1, will use DDP for training.
batch_size: 16
save_checkpoint_dir: /workspace/finetune_with_new_cabinet_data_6k_self_collision
max_epochs: 50
experiment_name: finetune_with_new_cabinet_data_6k_self_collision
description: "Best model finetuned on cabinet_6k dataset with self-collision loss"
