train_mode: "pretrain"

training_model_parameters:
    point_match_loss_weight: 1
    collision_loss_weight: 5

data_module_parameters:
  data_dir: /data/mpinets_hybrid_training_data_small
  trajectory_key: 'global_solutions' # Could also use 'global_solutions' for the global expert
  num_obstacle_points: 4096
  num_target_points: 128
  random_scale: 0.015
shared_parameters:
    num_robot_points: 2048

model_path: null
checkpoint_interval: 10
validation_interval: 3000
gpus: 1 # If > 1, will use DDP for training.
batch_size: 16
save_checkpoint_dir: /workspace/mpinets_pretrain
experiment_name: Test_pretrain_MPINets
description: "Test training job for MPINets with global_solutions data."
