train_mode: "pretrain"

training_model_parameters:
    point_match_loss_weight: 1
    collision_loss_weight: 5

data_module_parameters:
  data_dir: /data/ompl_cubby_6k
  trajectory_key: 'global_solutions' # Could also use 'global_solutions' for the global expert
  num_obstacle_points: 4096
  num_target_points: 128
  random_scale: 0.015
shared_parameters:
    num_robot_points: 2048

model_path: null
checkpoint_interval: 10
validation_interval: 3000
gpus: 1 # If > 1, will use DDP for training.
batch_size: 16
save_checkpoint_dir: /workspace/mpinets_pretrain
experiment_name: pretrain_cubby_6k
description: "Pretraining on the cubby dataset with 6k trajectories."
